### ISSUE TITLE
Exception in NodeLeader

### ISSUE THREAD

**Issue by merl111** [CityOfZion/neo-python#915]
### Current behavior
An exception is thrown due to `.value` is not an attribute or method of `str`
```
[C 190317 10:59:46 _observer:131]
    Traceback (most recent call last):
      File "/home/merl/venv/lib/python3.7/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
        current.result = callback(current.result, *args, **kw)
      File "/home/merl/neo-python/neo/Network/NodeLeader.py", line 693, in clientConnectionFailed
        logger.debug(f"Failed connecting to {address} {ce.args[0].value}")
    AttributeError: 'str' object has no attribute 'value'

```
### How to reproduce
start an api-server with 

`bin/np-api-server --mainnet --port-rpc 10332 --port-rest 8080 `

### Your environment

- OS: 4.15.0-38-generic #41-Ubuntu
- neo-python version: v0.8.4
- Python version: 3.7.0

### Possible solution
```
diff --git a/neo/Network/NodeLeader.py b/neo/Network/NodeLeader.py
index 6f99be78..c2743769 100644
--- a/neo/Network/NodeLeader.py
+++ b/neo/Network/NodeLeader.py
@@ -690,7 +690,7 @@ class NodeLeader:
         elif type(err.value) == error.ConnectError:
             ce = err.value
             if len(ce.args) > 0:
-                logger.debug(f"Failed connecting to {address} {ce.args[0].value}")
+                logger.debug(f"Failed connecting to {address} {ce.args[0]}")
             else:
                 logger.debug(f"Failed connecting to {address}")
         else:

```
As this is a very minor problem, I am not sure if a PR is necessary?

**Comment by ixje** [comment]
Hi, 
Thanks and we're aware. This has already been fixed in the `development` some time ago so no need to PR. We are also redoing the networking side so it will be obsolete in the near future, thanks!

**Comment by merl111** [comment]
Thank you for letting me know, I have checked the development branch and I could still see it in there, that's why I have opened and issue, but if you are already aware of that I am happy.

**Comment by ixje** [comment]
Oh you're right. It looked so similar to a previous one that misjudged it. I'll re-open such that others can find it and then close once the new networking is in. Thanks again for reporting!
