### ISSUE TITLE
ico_template.avm is an invalid parameter

### ISSUE THREAD

**Issue by adarshaJha** [CityOfZion/neo-python#938]
i am trying to deploy thor's ico smart contract, i was able to compile it and generate the .avm file but when i  run this command in np-prompt : 
**wallet import /home/adarsh.jha/Documents/neoproject/neo-ico-template/ico_te
mplate.avm 0702  False False** 

it gives me an error : 
**/home/adarsh.jha/Documents/neoproject/neo-ico-template/ico_template.avm is an invalid parameter**

**Comment by ixje** [comment]
what are you trying to do? Deploy the contract on the network or import the thor contract address?
For the former use `sc deploy` for the latter use `wallet import contract_addr `. Add `help` behind the commands to see the correct usage.

**Comment by adarshaJha** [comment]
@ixje i'm trying to deploy the contract on the network. i have already created a .avm file ( by compiling the thor contract ). I'm looking to use the same contract for my own demo app which launches ico on neo.

**Comment by adarshaJha** [comment]
@ixje  thanks for commenting, i found out what wrong i was doing. I was using import command rather i should have used sc deploy path _of_file  false false false 070202 02

but now it's giving me insufficient funds error. i went here https://neofaucet.info/account 
and cliamed 1500 neos but still wallet on the local cli doesn't refresh the data.

**Comment by ixje** [comment]
because you didn't follow the issue template, I can't tell what version you're using. There is an issue with the latest version where it _locally_ holds the wrong balance value after a deploy. That could be the issue here, use `wallet rebuild`  to solve that.

**Comment by ixje** [comment]
Given the inactivity of the issue I'm assuming it is resolved. If not please comment so we can reopen.

**Comment by adarshaJha** [comment]
i tried doing wallet rebuild but still getting the same error. not able to get balance.

**Comment by ixje** [comment]
I can't tell what version you are running because you decided to ignore the issue template. I cannot help you until you provide the requested information.

**Comment by adarshaJha** [comment]
@ixje  sorry, could you please help how to use issue template ? or which version i should use in order to do it.

**Comment by ixje** [comment]
when you open an issue you get a set of questions to answer. Specifically:

### Current behavior
- Are you using the latest available version? If not, first update and verify the problem still exists.
- What is the problem?
- Include a screenshot if it makes sense.

### Expected behavior

- What should be happening?
- Include a screenshot if it makes sense.

### How to reproduce

- Please explain the steps to reproduce the problem. If you are having an issue with your machine or build tools, the issue belongs on another repository as that is outside of the scope of this project.

### Your environment

Let us know in what environment you're running into the issue:

- OS: (Windows version/Linux distro/OSX version) 
- neo-python version: (hint: use `np-prompt --version`)
- Python version: (hint: `python -V`)
